<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <Version>1.0.1.4</Version>
    <PackageProjectUrl>https://github.com/Abyeon/Buildingway</PackageProjectUrl>
    <PackageLicenseExpression>AGPL-3.0-or-later</PackageLicenseExpression>
    <IsPackable>false</IsPackable>
    <Configurations>Release;Debug</Configurations>
    <Platforms>AnyCPU</Platforms>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Update="DalamudPackager" Version="15.0.0" />
    <PackageReference Update="DotNet.ReproducibleBuilds" Version="2.0.2" />
    <PackageReference Include="ECommons" Version="3.2.0.19" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\AbeUtils\AbeUtils\AbeUtils.csproj" />
    <ProjectReference Include="..\Anyder\Anyder\Anyder.csproj" />
  </ItemGroup>
</Project>
